"""initial

Revision ID: 0b46fc26195d
Revises: 
Create Date: 2021-06-27 23:39:45.474655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b46fc26195d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Text(), server_default='', nullable=True),
    sa.Column('task', sa.Text(length=250), nullable=True),
    sa.Column('status', sa.Text(), server_default='ToDo', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
